spring.application.name=food-ai-flatform-server
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/food_ai_platform?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:food_ai_platform}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:food_ai_platform}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
